import gtk

store = gtk.ListStore(str, gtk.gdk.Pixbuf)

longa = gtk.gdk.pixbuf_new_from_file_at_size("data/images/longa.png", 16, 16)
cuadrada = gtk.gdk.pixbuf_new_from_file_at_size("data/images/cuadrada.png", 16, 16)
redonda = gtk.gdk.pixbuf_new_from_file_at_size("data/images/redonda.png", 16, 16)
blanca = gtk.gdk.pixbuf_new_from_file_at_size("data/images/blanca.png", 32, 16)
negra = gtk.gdk.pixbuf_new_from_file_at_size("data/images/negra.png", 16, 16)
corchea = gtk.gdk.pixbuf_new_from_file_at_size("data/images/corchea.png", 16, 16)
semicorchea = gtk.gdk.pixbuf_new_from_file_at_size("data/images/semicorchea.png", 16, 16)
fusa = gtk.gdk.pixbuf_new_from_file_at_size("data/images/fusa.png", 16, 16)
semifusa = gtk.gdk.pixbuf_new_from_file_at_size("data/images/semifusa.png", 16, 16)
garrapatea = gtk.gdk.pixbuf_new_from_file_at_size("data/images/garrapatea.png", 16, 16)
semigarrapatea = gtk.gdk.pixbuf_new_from_file_at_size("data/images/semigarrapatea.png", 16, 16)

slonga = gtk.gdk.pixbuf_new_from_file_at_size("data/images/silencio_longa.png", 16, 16)
scuadrada = gtk.gdk.pixbuf_new_from_file_at_size("data/images/silencio_cuadrada.png", 16, 16)
sredonda = gtk.gdk.pixbuf_new_from_file_at_size("data/images/silencio_redonda.png", 16, 16)
sblanca = gtk.gdk.pixbuf_new_from_file_at_size("data/images/silencio_blanca.png", 16, 16)
snegra = gtk.gdk.pixbuf_new_from_file_at_size("data/images/silencio_negra.png", 16, 16)
scorchea = gtk.gdk.pixbuf_new_from_file_at_size("data/images/silencio_corchea.png", 16, 16)
ssemicorchea = gtk.gdk.pixbuf_new_from_file_at_size("data/images/silencio_semicorchea.png", 16, 16)
sfusa = gtk.gdk.pixbuf_new_from_file_at_size("data/images/silencio_fusa.png", 16, 16)
ssemifusa = gtk.gdk.pixbuf_new_from_file_at_size("data/images/silencio_semifusa.png", 16, 16)
sgarrapatea = gtk.gdk.pixbuf_new_from_file_at_size("data/images/silencio_garrapatea.png", 16, 16)
ssemigarrapatea = gtk.gdk.pixbuf_new_from_file_at_size("data/images/silencio_semigarrapatea.png", 16, 16)

store.append(["Longa", longa])
store.append(["Cuadrada", cuadrada])
store.append(["Redonda", redonda])
store.append(["Blanca", blanca])
store.append(["Negra", negra])
store.append(["Corchea", corchea])
store.append(["Semicorchea", semicorchea])
store.append(["Fusa", fusa])
store.append(["Semifusa", semifusa])
store.append(["Garrapatea", garrapatea])
store.append(["Semigarrapatea", semigarrapatea])

store.append(["Silencio de Longa", slonga])
store.append(["Silencio de Cuadrada", scuadrada])
store.append(["Silencio de Redonda", sredonda])
store.append(["Silencio de Blanca", sblanca])
store.append(["Silencio de Negra", snegra])
store.append(["Silencio de Corchea", scorchea])
store.append(["Silencio de Semicorchea", ssemicorchea])
store.append(["Silencio de Fusa", sfusa])
store.append(["Silencio de Semifusa", ssemifusa])
store.append(["Silencio de Garrapatea", sgarrapatea])
store.append(["Silencio de Semigarrapatea", ssemigarrapatea])

combo = gtk.ComboBox(store)

renderer = gtk.CellRendererText()
renderer.set_fixed_size(160, 20)
combo.pack_start(renderer, True)
combo.add_attribute(renderer, "text", 0)

renderer = gtk.CellRendererPixbuf()
combo.pack_start(renderer, False)
combo.add_attribute(renderer, "pixbuf", 1)

#window = gtk.Window()
#window.add(combo)
#window.show_all()

#window.connect('delete-event', lambda w, e: gtk.main_quit())

#gtk.main()
