import gtk
prefix_path = "data/images/"

lista_simbolos = [gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "longa.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "cuadrada.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "redonda.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "blanca.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "negra.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "corchea.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "semicorchea.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "fusa.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "semifusa.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "garrapatea.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "semigarrapatea.png", 50, 48),#
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "silencio_longa.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "silencio_cuadrada.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "silencio_redonda.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "silencio_blanca.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "silencio_negra.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "silencio_corchea.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "silencio_semicorchea.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "silencio_fusa.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "silencio_semifusa.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "silencio_garrapatea.png", 50, 48),
				  gtk.gdk.pixbuf_new_from_file_at_size(prefix_path + "silencio_semigarrapatea.png", 50, 48)]

lista_nombres = ["longa",
				  "cuadrada",
				  "redonda",
				  "blanca",
				  "negra",
				  "corchea",
				 "semicorchea",
				  "fusa",
				  "semifusa",
				  "garrapatea",
				  "semigarrapatea",#
				  "silencio_longa",
				  "silencio_cuadrada",
				  "silencio_redonda",
				  "silencio_blanca",
				  "silencio_negra",
				  "silencio_corchea",
				  "silencio_semicorchea",
				  "silencio_fusa",
				  "silencio_semifusa",
				  "silencio_garrapatea",
				  "silencio_semigarrapatea"]
